# SPDX-FileCopyrightText: Â© 2025 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT
 
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: oauth2-proxy-nginx-gw-cluster-local
  namespace: security
spec:
  parentRefs:
    - name: nginx-cluster-local
      namespace: nginx-gw
      sectionName: https
  hostnames:
    - k2s.cluster.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /oauth2
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: X-Forwarded-Proto
                value: https
              - name: X-Forwarded-Host
                value: k2s.cluster.local
      backendRefs:
        - name: oauth2-proxy
          port: 4180
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-nginx-gw-cluster-local
  namespace: security
spec:
  parentRefs:
    - name: nginx-cluster-local
      namespace: nginx-gw
      sectionName: https
  hostnames:
    - k2s.cluster.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /keycloak
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: X-Forwarded-Proto
                value: https
              - name: X-Forwarded-Host
                value: k2s.cluster.local
      backendRefs:
        - name: keycloak
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: security-to-nginx-gw
  namespace: nginx-gw
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: security
  to:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: nginx-cluster-local