# SPDX-FileCopyrightText: Â© 2025 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../ingress-traefik
- middleware.yaml

# ~1 in a patch's path means "/" as part of the key name
patches:
- patch: |-
    - op: replace
      path: "/metadata/annotations/traefik.ingress.kubernetes.io~1router.middlewares"
      value: "security-oauth2-proxy-forwarder-signin@kubernetescrd,rollout-oauth2-proxy-auth@kubernetescrd"
  target:
    kind: Ingress
    name: rollout-traefik-cluster-local
    namespace: rollout

