# SPDX-FileCopyrightText: Â© 2025 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/k2s/" # Location of package manifests
    schedule:
      interval: daily
      time: "17:00" # time in UTC
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "gomod"    
    ignore:
      - dependency-name: sigs.k8s.io/gateway-api
        update-types: [version-update:semver-major, version-update:semver-minor]
    groups:
      kube:
        patterns:
          - k8s.io/*

  # - package-ecosystem: "docker"
  #   directory: "/addons/dicom/manifests/dicom/"
  #   schedule:
  #     interval: daily
  #     time: "17:00" # time in UTC
  #   open-pull-requests-limit: 1
  #   allow:
  #     - dependency-type: "direct"
  #   labels:
  #     - "dependencies"
  #     - "addons"
  #     - "dicom"
      
#  - package-ecosystem: "github-actions"
#    directories:
#    - "/"
#    - ".github/workflows/*"
#    schedule:
#      interval: "daily"
#      time: "16:50"
#    open-pull-requests-limit: 1
