# SPDX-FileCopyrightText: Â© 2025 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/k2s/" # Location of package manifests
    schedule:
      interval: daily
      time: "17:00" # time in UTC
    open-pull-requests-limit: 4
    ignore:
      - dependency-name: sigs.k8s.io/gateway-api
        update-types: [version-update:semver-major, version-update:semver-minor]
    groups:
      kube:
        patterns:
          - k8s.io/*

  - package-ecosystem: "github-actions"
    directories:
    - "/"
    - ".github/workflows/*"
    schedule:
      interval: "daily"
      time: "16:50"
    open-pull-requests-limit: 1
