# SPDX-FileCopyrightText: Â© 2026 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: registry-nginx-gw-http
  namespace: registry
spec:
  parentRefs:
    - name: nginx-cluster-local
      namespace: nginx-gw
      sectionName: registry-http
  hostnames:
    - k2s.registry.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: registry
          port: 5000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: registry-nginx-gw-https
  namespace: registry
spec:
  parentRefs:
    - name: nginx-cluster-local
      namespace: nginx-gw
      sectionName: registry-https
  hostnames:
    - k2s.registry.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: registry
          port: 5000
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: registry-nginx-gw-reference-grant
  namespace: nginx-gw
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: registry
  to:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: nginx-cluster-local
---
apiVersion: policy.linkerd.io/v1beta3
kind: Server
metadata:
  name: registry-nginx-gw-server
  namespace: registry
spec:
  podSelector:
    matchLabels:
      app: registry
  port: 5000
  proxyProtocol: HTTP/1
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: registry-nginx-gw-server-authorization
  namespace: registry
spec:
  server:
    name: registry-nginx-gw-server
  client:
    unauthenticated: true
