# SPDX-FileCopyrightText: Â© 2026 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dicom-nginx-gw-cluster-local-https
  namespace: dicom
spec:
  parentRefs:
    - name: nginx-cluster-local
      namespace: nginx-gw
      sectionName: https
  hostnames:
    - k2s.cluster.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /dicom
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: X-Forwarded-Proto
                value: https
              - name: X-Forwarded-Host
                value: k2s.cluster.local
              - name: Access-Control-Allow-Origin
                value: "*"
      backendRefs:
        - name: dicom
          port: 8042
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dicom-nginx-gw-cluster-local-http
  namespace: dicom
spec:
  parentRefs:
    - name: nginx-cluster-local
      namespace: nginx-gw
      sectionName: http
  hostnames:
    - k2s.cluster.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /dicom
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: X-Forwarded-Proto
                value: http
              - name: X-Forwarded-Host
                value: k2s.cluster.local
              - name: Access-Control-Allow-Origin
                value: "*"
      backendRefs:
        - name: dicom
          port: 8042
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: dicom-to-nginx-gw
  namespace: nginx-gw
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: dicom
  to:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: nginx-cluster-local
