# SPDX-FileCopyrightText: Â© 2026 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT
---
# Source: nginx-gateway-fabric/templates/certs-job.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-gw-cert-generator
  namespace: nginx-gw
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/name: nginx-gw
    app.kubernetes.io/instance: nginx-gw
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install
automountServiceAccountToken: false
---
# Source: nginx-gateway-fabric/templates/certs-job.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-gw-cert-generator
  namespace: nginx-gw
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/name: nginx-gw
    app.kubernetes.io/instance: nginx-gw
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - get
---
# Source: nginx-gateway-fabric/templates/certs-job.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-gw-cert-generator
  namespace: nginx-gw
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/name: nginx-gw
    app.kubernetes.io/instance: nginx-gw
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-gw-cert-generator
subjects:
- kind: ServiceAccount
  name: nginx-gw-cert-generator
  namespace: nginx-gw
---
# Source: nginx-gateway-fabric/templates/certs-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-gw-cert-generator
  namespace: nginx-gw
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/name: nginx-gw
    app.kubernetes.io/instance: nginx-gw
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
spec:
  template:
    metadata:
      annotations:
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - generate-certs
        - --service=nginx-gw-controller
        - --cluster-domain=cluster.local
        - --server-tls-secret=server-tls
        - --agent-tls-secret=agent-tls
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/nginx/nginx-gateway-fabric:2.3.0
        imagePullPolicy: IfNotPresent
        name: cert-generator
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 101
          runAsGroup: 1001
      restartPolicy: Never
      serviceAccountName: nginx-gw-cert-generator
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
  ttlSecondsAfterFinished: 30
