# SPDX-FileCopyrightText: Â© 2025 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: nginx-gw
    app.kubernetes.io/name: nginx-gw
    app.kubernetes.io/version: 1.6.2
  name: nginx-gw
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  - gateways
  - httproutes
  - referencegrants
  - grpcroutes
  verbs:
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes/status
  - gateways/status
  - gatewayclasses/status
  - grpcroutes/status
  verbs:
  - update
- apiGroups:
  - gateway.nginx.org
  resources:
  - nginxgateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.nginx.org
  resources:
  - nginxproxies
  - clientsettingspolicies
  - observabilitypolicies
  - upstreamsettingspolicies
  verbs:
  - list
  - watch
- apiGroups:
  - gateway.nginx.org
  resources:
  - nginxgateways/status
  - clientsettingspolicies/status
  - observabilitypolicies/status
  - upstreamsettingspolicies/status
  verbs:
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: nginx-gw
#   labels:
#     app.kubernetes.io/part-of: nginx-gw
#     app.kubernetes.io/name: nginx-gw
#     app.kubernetes.io/instance: nginx-gw
#     app.kubernetes.io/version: "2.2.2"
# rules:
# - apiGroups:
#   - ""
#   resources:
#   - secrets
#   - configmaps
#   - serviceaccounts
#   - services
#   verbs:
#   - create
#   - update
#   - delete
#   - list
#   - get
#   - watch
# - apiGroups:
#   - apps
#   resources:
#   - deployments
#   - daemonsets
#   verbs:
#   - create
#   - update
#   - delete
#   - list
#   - get
#   - watch
# - apiGroups:
#   - autoscaling
#   resources:
#   - horizontalpodautoscalers
#   verbs:
#   - create
#   - update
#   - delete
#   - list
#   - get
#   - watch
# - apiGroups:
#   - ""
#   resources:
#   - namespaces
#   - pods
#   verbs:
#   - get
#   - list
#   - watch
# - apiGroups:
#   - apps
#   resources:
#   - replicasets
#   verbs:
#   - get
#   - list
# - apiGroups:
#   - ""
#   resources:
#   - nodes
#   verbs:
#   - list
# - apiGroups:
#   - ""
#   resources:
#   - events
#   verbs:
#   - create
#   - patch
# - apiGroups:
#   - discovery.k8s.io
#   resources:
#   - endpointslices
#   verbs:
#   - list
#   - watch
# - apiGroups:
#   - authentication.k8s.io
#   resources:
#   - tokenreviews
#   verbs:
#   - create
# - apiGroups:
#   - gateway.networking.k8s.io
#   resources:
#   - gatewayclasses
#   - gateways
#   - httproutes
#   - referencegrants
#   - grpcroutes
#   verbs:
#   - list
#   - watch
# - apiGroups:
#   - gateway.networking.k8s.io
#   resources:
#   - httproutes/status
#   - gateways/status
#   - gatewayclasses/status
#   - grpcroutes/status
#   verbs:
#   - update
# - apiGroups:
#   - gateway.nginx.org
#   resources:
#   - nginxgateways
#   verbs:
#   - get
#   - list
#   - watch
# - apiGroups:
#   - gateway.nginx.org
#   resources:
#   - nginxproxies
#   - clientsettingspolicies
#   - observabilitypolicies
#   - upstreamsettingspolicies
#   verbs:
#   - list
#   - watch
# - apiGroups:
#   - gateway.nginx.org
#   resources:
#   - nginxgateways/status
#   - clientsettingspolicies/status
#   - observabilitypolicies/status
#   - upstreamsettingspolicies/status
#   verbs:
#   - update
# - apiGroups:
#   - coordination.k8s.io
#   resources:
#   - leases
#   verbs:
#   - create
#   - get
#   - update
# - apiGroups:
#   - apiextensions.k8s.io
#   resources:
#   - customresourcedefinitions
#   verbs:
#   - list
#   - watch