# SPDX-FileCopyrightText: Â© 2026 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/instance: nginx-gw
    app.kubernetes.io/name: nginx-gw
    app.kubernetes.io/version: "2.3.0"
  name: nginx-gw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-gw
subjects:
- kind: ServiceAccount
  name: nginx-gw
  namespace: nginx-gw
# ---
# apiVersion: v1
# data:
#   main.conf: |
#     error_log stderr info;
# kind: ConfigMap
# metadata:
#   labels:
#     helm.sh/chart: nginx-gateway-fabric-2.3.0
#     app.kubernetes.io/instance: nginx-gw
#     app.kubernetes.io/name: nginx-gw
#     app.kubernetes.io/version: "2.3.0"
#   name: nginx-includes-bootstrap
#   namespace: nginx-gw