# SPDX-FileCopyrightText: Â© 2026 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: nginx-gw
    app.kubernetes.io/name: nginx-gw
    app.kubernetes.io/version: "2.3.0"
  name: nginx-gw-controller
  namespace: nginx-gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: nginx-gw
      app.kubernetes.io/name: nginx-gw
  template:
    metadata:
      annotations:
        prometheus.io/port: "9113"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: nginx-gw
        app.kubernetes.io/name: nginx-gw
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - controller
        - --gateway-ctlr-name=gateway.nginx.org/nginx-gw-controller
        - --gatewayclass=nginx-gw
        - --config=nginx-gw-config
        - --service=nginx-gw-controller
        - --agent-tls-secret=agent-tls
        - --metrics-port=9113
        - --health-port=8081
        - --leader-election-lock-name=nginx-gw-leader-election
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/instance']
        - name: IMAGE_NAME
          value: ghcr.io/nginx/nginx-gateway-fabric:2.3.0
        image: ghcr.io/nginx/nginx-gateway-fabric:2.3.0
        imagePullPolicy: IfNotPresent
        name: nginx-gw
        ports:
        - name: agent-grpc
          containerPort: 8443
        - name: metrics
          containerPort: 9113
        - name: health
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 3
          periodSeconds: 1
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 101
          runAsGroup: 1001
        volumeMounts:
        - name: nginx-agent-tls
          mountPath: /var/run/secrets/ngf
      terminationGracePeriodSeconds: 30
      serviceAccountName: nginx-gw
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
      volumes:
      - name: nginx-agent-tls
        secret:
          secretName: server-tls

