# SPDX-FileCopyrightText: Â© 2026 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: nginx-gw
    app.kubernetes.io/name: nginx-gw
    app.kubernetes.io/version: 2.3.0
  name: nginx-gw-cert-generator
  namespace: nginx-gw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-gw-cert-generator
subjects:
- kind: ServiceAccount
  name: nginx-gw-cert-generator
  namespace: nginx-gw