# SPDX-FileCopyrightText: Â© 2026 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-gw
  namespace: nginx-gw
  labels:
    helm.sh/chart: nginx-gateway-fabric-2.3.0
    app.kubernetes.io/instance: nginx-gw
    app.kubernetes.io/name: nginx-gw
    app.kubernetes.io/version: "2.3.0"
  annotations:
    {}
automountServiceAccountToken: false
