# SPDX-FileCopyrightText: Â© 2023 Siemens Healthcare GmbH
#
# SPDX-License-Identifier: MIT

---
# Source: kube-prometheus-stack/templates/prometheus/additionalScrapeConfigs.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kube-prometheus-stack-prometheus-scrape-confg
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus-scrape-confg
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/version: "47.1.0"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-47.1.0
    release: "kube-prometheus-stack"
    heritage: "Helm"
stringData:
  additional-scrape-configs.yaml: |-
    - "job_name": "windows-exporter"
      "relabel_configs":
      - "action": "replace"
        "regex": "(.*)"
        "replacement": "$1"
        "source_labels":
        - "__meta_kubernetes_endpoint_address_target_name"
        "target_label": "instance"
      "static_configs":
      - "targets":
        - "172.19.1.1:9100"
        - "172.19.1.101:9100"
    - "job_name": "nvidia-exporter"
      "relabel_configs":
      - "action": "replace"
        "regex": "(.*)"
        "replacement": "$1"
        "source_labels":
        - "__meta_kubernetes_endpoint_address_target_name"
        "target_label": "instance"
      "static_configs":
      - "targets":
        - "172.19.1.100:30094"