# SPDX-FileCopyrightText: Â© 2024 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT

# Placeholder for secure traefik ingress with KeyCloak/Hydra integration
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../ingress-traefik/rollout-ingress-traefik.yaml
