# SPDX-FileCopyrightText: Â© 2025 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-gateway-cert-generator
  namespace: nginx-gateway
  labels:
    app.kubernetes.io/part-of: nginx-gateway
    app.kubernetes.io/name: nginx-gateway
    app.kubernetes.io/instance: nginx-gateway
    app.kubernetes.io/version: "2.2.2"
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-gateway-cert-generator
  namespace: nginx-gateway
  labels:
    app.kubernetes.io/part-of: nginx-gateway
    app.kubernetes.io/name: nginx-gateway
    app.kubernetes.io/instance: nginx-gateway
    app.kubernetes.io/version: "2.2.2"
  annotations:
    "helm.sh/hook": pre-install
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - update
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-gateway-cert-generator
  namespace: nginx-gateway
  labels:
    app.kubernetes.io/part-of: nginx-gateway
    app.kubernetes.io/name: nginx-gateway
    app.kubernetes.io/instance: nginx-gateway
    app.kubernetes.io/version: "2.2.2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-gateway-cert-generator
subjects:
- kind: ServiceAccount
  name: nginx-gateway-cert-generator
  namespace: nginx-gateway
---
apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-gateway-cert-generator
  namespace: nginx-gateway
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/part-of: nginx-gateway
    app.kubernetes.io/name: nginx-gateway
    app.kubernetes.io/instance: nginx-gateway
    app.kubernetes.io/version: "2.2.2"
spec:
  template:
    metadata:
      annotations:
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - generate-certs
        - --service=nginx-gateway
        - --cluster-domain=cluster.local
        - --server-tls-secret=server-tls
        - --agent-tls-secret=agent-tls
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/nginx/nginx-gateway-fabric:2.2.2
        imagePullPolicy: IfNotPresent
        name: cert-generator
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 101
          runAsGroup: 1001
      restartPolicy: Never
      serviceAccountName: nginx-gateway-cert-generator
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
  ttlSecondsAfterFinished: 30