# SPDX-FileCopyrightText: Â© 2025 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

namespace: nginx-gateway

resources:
  - namespace.yaml
  # - crds/gateway.nginx.org_clientsettingspolicies.yaml
  # - crds/gateway.nginx.org_nginxgateways.yaml
  # - crds/gateway.nginx.org_nginxproxies.yaml
  # - crds/gateway.nginx.org_observabilitypolicies.yaml
  # - crds/gateway.nginx.org_snippetsfilters.yaml
  # - crds/gateway.nginx.org_upstreamsettingspolicies.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - service.yaml
  - deployment.yaml
  - gatewayclass.yaml
  - nginxgateway.yaml
  - nginxproxy.yaml
  - certs-job.yaml




