---
# Source: opensearch-dashboards/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opensearch-dashboards-dashboards
  namespace: logging
  labels:
    helm.sh/chart: opensearch-dashboards-2.16.0
    app.kubernetes.io/name: opensearch-dashboards
    app.kubernetes.io/instance: opensearch-dashboards
    app.kubernetes.io/version: "2.12.0"
    app.kubernetes.io/managed-by: Helm
