# SPDX-FileCopyrightText: Â© 2025 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../ingress-nginx

# ~1 in a patch's path means "/" as part of the key name
# Example:
# "/metadata/annotations/nginx.ingress.kubernetes.io~1auth-url" means:
# metadata:
#   annotations:
#     nginx.ingress.kubernetes.io/auth-url:
patches:
  - patch: |-
      - op: add
        path: "/metadata/annotations/nginx.ingress.kubernetes.io~1auth-url"
        value: "https://k2s.cluster.local/oauth2/auth"
      - op: add
        path: "/metadata/annotations/nginx.ingress.kubernetes.io~1auth-signin"
        value: "https://k2s.cluster.local/oauth2/start?rd=$escaped_request_uri"
      - op: add
        path: "/metadata/annotations/nginx.ingress.kubernetes.io~1auth-snippet"
        value: |
          auth_request_set $user  $upstream_http_x_auth_request_user;
          auth_request_set $email  $upstream_http_x_auth_request_email;
          proxy_set_header X-User  $user;
          proxy_set_header X-Email $email;
    target:
      kind: Ingress
      name: viewer-nginx-cluster-local
      namespace: viewer
