# SPDX-FileCopyrightText: Â© 2026 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: logging-nginx-gw-cluster-local-https
  namespace: logging
spec:
  parentRefs:
    - name: nginx-cluster-local
      namespace: nginx-gw
      sectionName: https
  hostnames:
    - k2s.cluster.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /logging
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: X-Forwarded-Proto
                value: https
              - name: X-Forwarded-Host
                value: k2s.cluster.local
      backendRefs:
        - name: opensearch-dashboards
          port: 5601
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: logging-nginx-gw-cluster-local-http
  namespace: logging
spec:
  parentRefs:
    - name: nginx-cluster-local
      namespace: nginx-gw
      sectionName: http
  hostnames:
    - k2s.cluster.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /logging
      filters:
        - type: RequestHeaderModifier
          requestHeaderModifier:
            add:
              - name: X-Forwarded-Proto
                value: http
              - name: X-Forwarded-Host
                value: k2s.cluster.local
      backendRefs:
        - name: opensearch-dashboards
          port: 5601
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: logging-nginx-gw-reference-grant
  namespace: nginx-gw
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: logging
  to:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: nginx-cluster-local
