# SPDX-FileCopyrightText: Â© 2023 Siemens Healthcare GmbH
#
# SPDX-License-Identifier: MIT
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    __NETWORK_INTERFACE_NAME__:
      addresses: [__NETWORK_ADDRESSES__]
      routes:
        - to: default
          via: __IP_GATEWAY__
      nameservers:
        addresses: [__DNS_IP_ADDRESSES__]