# SPDX-FileCopyrightText: Â© 2025 Siemens Healthineers AG
#
# SPDX-License-Identifier: MIT

# This ingress exposes the viewer angular application on https://k2s.cluster.local/viewer
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: viewer-nginx-gw-http
  namespace: viewer
spec:
  parentRefs:
    - name: nginx-cluster-local
      namespace: nginx-gw
      sectionName: http
  hostnames:
    - k2s.cluster.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /viewer
      backendRefs:
        - name: viewerwebapp
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: viewer-nginx-gw-https
  namespace: viewer
spec:
  parentRefs:
    - name: nginx-cluster-local
      namespace: nginx-gw
      sectionName: https
  hostnames:
    - k2s.cluster.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /viewer
      backendRefs:
        - name: viewerwebapp
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: viewer-nginx-gw-reference-grant
  namespace: nginx-gw
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: viewer
  to:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: nginx-cluster-local
